### PR TITLE
Gene search on geneset page

### PR DESCRIPTION
**Pull request by vincerubinetti**
- add gene api queries
- add `always_list` api flag where possible to always use arrays
- alter typescript types for genes and genesets
- change visibility from dropdown to checkbox
- remove GenesetEdit higher-order-component and make into page and sections
- refactor table component action button behavior to allow functions
- route /geneset/[ID] and /new to same page component
- some string casing util functions
- refactor and improve tooltip directive to correctly update
- add geneset page functionalities to add and remove genes, and show diff of changes
- add checkbox styles

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Reviewers, look at this page to see how it will look when creating new sets and editing sets you own:
https://deploy-preview-19--my-geneset.netlify.app/new

Look at this page for an example of viewing a non-editable (built-in or owned by someone else) set:
https://deploy-preview-19--my-geneset.netlify.app/geneset/VECCHI_GASTRIC_CANCER_ADVANCED_VS_EARLY_DN

**Review by dongbohu — APPROVED** [review]

**Comment by ravila4** [comment]
A couple of issues, besides improving search results, as discussed in [mygeneset.info/issues/#31](https://github.com/biothings/mygeneset.info/issues/31):

1. Restricting genesets to a single taxid. This has been been discussed in  [mygeneset.info/issues/#10]( https://github.com/biothings/mygeneset.info/issues/10) Custringrrently it is possible to create a geneset with genes from different species using the web interface.
Perhaps it would be good to move the species selection box to the top, near the other required fields:
image

2. Batch gene search. It would be nice if the user could input a comma-separated list of gene ids, and submit a batch query via POST. We need to think about the default search behavior.... perhaps it is better to switch all gene queries to POST? 

3.  I'm not sure if it is useful to include the "entrez", "ensembl", and "uniprot" fields in the search results. I think most users will identify the gene they want from the combination of name and symbol, and after they add it to their geneset, they can get the rest of the information.
image

**Comment by vincerubinetti** [comment]
@ravila4 

1. Is not resolved yet so I defaulted to allowing multiple. Once we decide for sure I can make this change.
2. This is coming in another PR
3. Columns can be added/deleted from the tables very easily so until we get user feedback I was just going to leave them in there. That may help for testing as well, to see all the fields.

**Comment by vincerubinetti** [comment]
@ravila4 Here's another reason to include more than just Name and Symbol:

image

**Comment by ravila4** [comment]
That's a good point... RNAs are definitely a special case.

**Pull request merged**
