### PR TITLE
add basic write geneset capabilities

### PR DESCRIPTION
**Pull request by vincerubinetti**
- install msw library for mocking api responses for testing
- refactor api request func
- add api funcs to create/update and delete geneset
- add summary of logged-in user's genesets to user page
- plugin functionality on geneset page to publish changes or delete
- add detailed table of logged-in user's genesets to build page
- add some api fixture data for testing

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@ravila4 With the last commit, the app seems to be in working order with regard to creating, updating, and deleting genesets. Once this is reviewed, we can merge and test in production. Then I can start on #29 and fix a bunch of other small things.

**Comment by ravila4** [comment]
@vincerubinetti It looks like the issue with making private genesets is becasuse key in the request body is being submitted as `isPublic` instead of `is_public`.

**Comment by vincerubinetti** [comment]
image

Please see [these lines of code](https://github.com/biothings/mygeneset.info-website/pull/28/files#diff-c54084fa99b705dfce9f5001b6014e7a00c493d5e54917b5584872666273a1f8R70-R74).

**Comment by ravila4** [comment]
It's working correctly for me now. On the UI end, I think it would  be nice to make the "X" buttons red on the add/remove genesets list, for greater contrast.

**Comment by ravila4** [comment]
@vincerubinetti I think we can merge this PR, everything is looking good now.

**Pull request merged**
