### PR TITLE
final touchups and fixes before release

### LINKED ISSUE #38: Final frontend updates
1. Display gene count in the 'Browse' and 'Your genesets' tables.
image

2. ~Enable sorting genesets by last updated date~. Sorting not possible, but we can display date. (Perhaps not high priority, but this is now possible) For curated datasets, the last update date can be retrieved from the `src.<datasource_name>.upload_date` field in: https://mygeneset.info/v1/metadata/. User and anonymous genesets should have a `updated` field.

3. Refine user experience when creating anonymous genesets:

- Anonymous users can only create public genesets, so if the user is logged out, it should not be possible to uncheck `visibility: public`.
image
- UI behavior after creating anonymous genesets. After a user creates an anonymous geneset, he may want to visit the url of the created geneset. We can either redirect him to the newly created geneset, and expect him to remember the url, or cache  a cookie in his browser and display a list of his recently created genesets in the 'Build' page. Right now, we redirect to the Build page, but no geneset id is displayed, therefore the user loses access to his geneset.

~4. Display Metrics in front page: (Number of requests in last 30 days)~

5. Display dates in "ago" format (with full/precies date on hover).

6. Error status for queries?

7. On creation of new geneset, redirect back to newly created geneset page.

8. Contact Marco about linking to new site from biothings website

9. Add favicons of logo.

### PR DESCRIPTION
**Pull request by vincerubinetti**
closes #38 

- add app description and url to env vars
- add favicon and share image
- add meta tags
- fix upload/download dates for curated genesets
- add component for showing time in "ago" format
- tweak tab title
- incorp geneset `count` field
- add window alert on error saving geneset (important)
- fix checkbox writeable when anonymous bug
- put all dates in "ago" format
- decided not to put date as column in geneset table because it takes up quite a bit of horizontal space. it is easy to add in if anyone ever requests it though.
- misc bug fixes

### CODE REVIEW

**Comment by ravila4** [comment]
This looks good! I like that there is tooltips on the update/download dates.

**Comment by ravila4** [comment]
I added some updates about the issue with the description field: https://github.com/biothings/mygeneset.info-website/issues/38#issuecomment-1311172207

I added some transformations on the backend to make sure it always stores a string in both the name and description fields, but you may want to fix the input on the request.

**Comment by vincerubinetti** [comment]
Latest commit fixes the description field bug where it becomes an array. This was due to how I was using the AppInput component for gene searching (where you could switch between single and multi-line modes, and have it split the controlled value as an array).

I simplified the component to just take strings (should be less error prone), but this slightly changes how the batch searching works. Now, if the input has any commas/tabs/newlines, it splits it into array and performs a batch search. Otherwise, just a regular string search. This is now independent of whether the input is expanded to multi-line or not. Do you think this is okay? Now the multi-line toggle button really just serves to expand the search box to give the user more space to see (and ability to resize it).

**Comment by ravila4** [comment]
@vincerubinetti I actually like the new behavior better. It was a bit unintuitive that multiline mode returned different results than single line mode.

**Comment by ravila4** [comment]
I tested the feature using this gene list (and species = human):
`ADAM17,APH1A,APH1B,NCSTN,NFKB1,NGFR,PSEN1,PSEN2,PSENEN,RELA,TRAF6`

It is returning the same results with the new batch search method as before, however I did notice one unexpected thing. The first page of results says 1 to 10 of 11, but actually displays 11 rows.  When I go to the second row, I get a bunch of empty rows:

First page:
image

Second page:
image

**Comment by ravila4** [comment]
Also, I was wondering if it might be good to add a way to select all of the results at the same time?

**Comment by vincerubinetti** [comment]
Okay, I fixed the pagination error. If you remember, a while ago I switched from doing all the pagination/filtering/sorting on the frontend (and doing a giant query to get all/most of the results), to letting the backend handle all of that. I didn't realize that the mygene batch search endpoint did not accept the `size` and `from` parameters. I've now fixed this to do the pagination on the frontend for that specific case.

**Comment by ravila4** [comment]
It looks good. Would it be possible to make the pagination redirect back to the "Add" anchor link? It would be better than having to scroll back up when paginating.
like this: https://deploy-preview-39--my-geneset.netlify.app/new#add

**Comment by vincerubinetti** [comment]
Added the "select/deselect all" buttons, though they only work on a per page basis, since the pagination is done on the backend, and also since I'm hesitant to give the user a way to select 1000 genes without at least looking them over.

Also added the scroll to add section, good idea.

Also truncated long plain text in tables (with ability to click to expand).

**Comment by ravila4** [comment]
Nice! I agree, it's better to encourage users to review all pages. The pagination is a lot smoother now, and truncating the text is a good idea.

**Comment by ravila4** [comment]
I think the current behavior is good. I like that the list of species refreshes dynamically as you add/remove genes. I think we can keep it as is, and I'll fix the backend to be compatible for all genesets.

**Comment by ravila4** [comment]
It's always better to delete code rather than add it!

**Comment by vincerubinetti** [comment]
Added the taxon id and corresponding species scientific name to the download options.

**Comment by ravila4** [comment]
Noticed an issue with pagination in cases when the

**Comment by ravila4** [comment]
Noticed an issue with pagination in cases where you filter a gene list by species, but leave the query string blank. When you switch pages, the page numbers change, but the gene list doesn't.

**Comment by vincerubinetti** [comment]
I think https://github.com/biothings/mygeneset.info-website/pull/39/commits/54631428af553fdc04b554dee3173eb3778d41fc fixes it.

**Comment by vincerubinetti** [comment]
It looks like the newer shorter prefixed IDs are ready: https://github.com/biothings/mygeneset.info/issues/63

I was going to say we wait until that's done before we release. Also remember to delete all of our dumb test genesets! Or maybe make some meaningful/clean user genesets as examples.

**Comment by ravila4** [comment]
The fix looks good!

Yes, we need to delete the test genesets. It would be good to have some real examples. Perhaps we could import some from Tribe?

**Pull request merged**
