### PR TITLE
Revamp entire app

### LINKED ISSUE #23: Clickable anchor links in 'About' page
It would be niece to be able to directly link to different sections of the about page such as:

  https://mygeneset.info/about#faqs
  https://mygeneset.info/about#cite

Currently, all these links redirect to the about page.

Also, an icon button next to each subtitle to jump to this specific url might be useful. Something like:  **FAQs [⚓]( https://mygeneset.info/about#faqs)**

### LINKED ISSUE #29: Spring cleaning
This project was halted in a somewhat half-finished state back in Summer 2021 (I think). Since then I've discovered many ways I could make this project cleaner. I'd like to finish these up so the app is in a nice clean state before we announce that it's released.

I expect that these items would take no longer than a week. The implementation of the oauth login and writing genesets has taken less than a week, so we are still within our estimates for this project. @cgreene Any objections?

- Convert project to the modern composition API. I did this with Monarch UI, and it was very quick (< 8 hours, and that was a much bigger code base), and had [immense benefits](https://github.com/monarch-initiative/monarch-ui-new/issues/97).
- Offload custom tooltip code to tippy library.
- Maybe offload custom JSON viewer code to [vue-json-loader](https://www.npmjs.com/package/vue-json-viewer)? It was a nice exercise to make my own, but maybe better for maintainability to just use third party.
- Update `vue-cli` stuff. This would fix some weird linting issues, and probably help build issues on later version of node that Ricardo was running into.
- Increase linting threshold to all recommended rules, and fix.
- Rework custom table component to make use of named slots instead of format functions.
- Reorganize view folder structure a bit.
- Be better about showing statuses for queries, like loading and error.
- Get extra information, e.g. the "96,290 genesets created" and the placeholder gray boxes on the home page. Or if we can't get that info right now, just hide those sections for now.
- Aria label for "Try It Out" code box on API page?
- Split gh-actions workflows into tests and deploy, [like in Monarch UI](https://github.com/monarch-initiative/monarch-ui-new/tree/main/.github/workflows)
- make trash/remove icons red, and delete geneset button red
- add way to set flag for api root/baseurl

### LINKED ISSUE #30: Anonymous user geneset building
Currently, the website's "Build" page allows users to build and download genesets while logged out. There is also a "Create" button that would allow the user to create an "anoymous" geneset in the database, but this feature is not implemented at the moment.

 We need to decide whether we want to support these two Build/Download features, and may need to implement a few things to make this workflows smoother.

**Downloading anonymous genesets** - This is mostly working, and I think it's a good idea to keep.
One thing that could be improved is offloading some of the geneset creation code to the backend. The benefit would be that the data would match exactly what the database would record if the user was logged in. One way to do it is to allow unauthenticated POST requests with the --dry_run flag (This could also be useful for testing). In this case, to download a geneset we simply fetch the JSON from the response, and transform it to csv/tsv/gmx formats if needed.

 **Creating anonymous genesets** - Not supported. Currently returns a 401 Unauthorized Error if user is not logged in. 
If we don't plan to support it, we should remove the button for logged out users, and update the text under the Login page's "Use As Guest" section.
I'm open to discussion into reasons to support it, but I think we would have to address a few questions on the backend namely:
1. If an anonymous user creates a geneset, who can edit/delete it? (Perhaps it could be temporary and auto-delete itself?)
2. How to keep track of changes, and avoid conflicts? e.g. If two people edit the same geneset at the same time.

I'll duplicate this issue in the mygeneset backend repository, to track any changes it may require in the backend.

### LINKED ISSUE #32: Show 'Source' info in geneset details page
Curated genesets have a field called 'source' (different from 'author' in user genesets). We could display this info instead of the blank Author field. @vincerubinetti up to you whether you want to rename the field label 'Author / Source', keep both fields, or change the text based on context.

image

### PR DESCRIPTION
**Pull request by vincerubinetti**
closes #32 
closes #30 
close #29 
close #23 

Overall, this is basically a rewrite of the entire app. #29 was supposed to be a full list of the things I was going to fix, but I ended up realizing that there were more problems with the old code than I thought. I now have much more experience with Vue and TypeScript, and was able to make many simplifications and improvements.

Sorry that this has taken long than the week that was estimated (ended up taking 2+ weeks, and had to attend to other matters). I also apologize that this will be very difficult to review. Despite these things, I think this was necessary.

Here is what this PR implements, roughly in order of the diff.

- increase sensitivity of eslint and conform to as many vue style guidelines as possible
- refactor github action workflows. split into separate workflows for prs and merging to main. split tests into separate jobs/checks. based on github actions workflows in `monarch-initiative/monarch-ui-new`
- upgrade packages as much as possible to latest versions. install font awesome, popper js, vueform/multiselect, vueuse, vuejsonpretty, etc.
- **convert entire app from options API to composition API**. [see here](https://github.com/monarch-initiative/monarch-ui-new/issues/97) for benefits.
- move global css to new global folder
- make global queries on app mount
- refactor api code to be more clean and consistent, separating backend data types from frontend datatypes
- add de-"stale"ing to api calls (latest call of a certain type always overrides previous calls) to avoid race conditions
- add some util funcs to get consistent human-readable labels, tooltips, and sortable/serializable identifiers for genes. use gene symbol for labels for more compact display.
- get site metadata (e.g. number of user genesets, number of private genesets, usage stats, curated source details, etc)
- get rid of api types file and move individual types to files where they appropriately belong
- make logo a vue component and allow animation on hover again
- move species icons to icons folder
- remove checkbox and radio asset svgs and use unified icon component instead
- consolidate the confusing split-up of header sub-components back into one single header component. same with footer.
- **rename most components** to be inline with vue style guides, namely that component names must be multi-word
- rename clickable component to button, and add new features and better control of appearance.
- make checkbox component for checks or radios
- rewrite checklist component for group of checkboxes or radio buttons. support explicit control group (name attribute)
- rework codeblock component
- make "detail" component
- rework feature component
- replace center component with more flexible flex component
- **make high-level geneset table component** that allows sorting by author, source, and count
- make heading component with anchors
- rework hero component
- make unified icon component for importing font awesome icons (instead of importing the whole font awesome font when we only use a small % of the total icons) or custom icons as svg
- rework input/textbox component, add clear button
- replace custom json view component with third party library
- add "pill" component for consistently showing non-editable lists of genes
- rework species select component
- make status component for showing loading, error, etc
- **rework table component to be completely controlled** (meaning pagination, filtering, etc takes place on backend and the frontend component just gets told what rows to show), and to make use of named slots instead of formatter functions. add slot for loading/empty status
- other small component reworks
- make global list of common components that don't need to be imported every time
- make list of font awesome icons to be able to be used
- get rid of sass mixins
- reduce global css a bit and move some styles out to dedicated components
- refactor main.ts a bit
- incorporate proper scroll behavior into vue router
- simplify typescript vue shims
- add global app metadata (user genesets, usage stats, etc) to vuex store
- add, delete, and modify util funcs as necessary
- replace custom tooltip directive with vue-tippy
- simplify page component logic wherever possible, refactor to composition api, rename and rearrange pages/sections
- simplify how /user page redirects to /login if not logged in, and vice versa
- add actual usage data numbers to api page
- on browse page, added controls to filter by type of geneset (user/curated/anonymous) and source (kegg/go/etc).
- add table of logged-in-user's genesets to build page
- **add high-level icons** to top of geneset page (and in geneset table as small column) that show whether geneset is new/editable/read-only, public/private, and user/curated/anonymous
- on geneset page, in "selected genes" section, **show selected genes as list of pill components** (with gene symbols instead of names) for more compact display, instead of table. list is searchable and sortable.
- rework geneset download section a bit. add option for including metadata about geneset (name, description, etc).
- add table of recent genesets to home page, along with actual geneset count metadata
- tidy up user page slightly
- add more json fixture data to MSW api mocking
- simplify vue config
- add more comments overall

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Note: If you run this app locally, all the API calls will be with mocked responses, which you can see in `/tests/fixtures/` `.json` files. You might notice some weird things because of this, like no matter what geneset you go to, it always has the same title/description/genes/etc properties, because that page is always just using that same file.

The deploy preview is NOT using mocked responses, which means that you can get actual data from the live database. But it also means you can't log in (because the authentication only works on the mygeneset.info domain), so that limits what you're able to test, like editing a personally created geneset.

I wonder if there's a way to get the best of both worlds.

**Comment by vincerubinetti** [comment]
Another question to resolve is whether anonymous genesets work as expected or not. With this PR, if you're not logged in and go to `/new` to create a new geneset, when it gets submitted the `author` field is just blank. Hopefully the backend is setup to handle that properly.

**Comment by vincerubinetti** [comment]
It was requested that we "keep" the sorting by name and number of genes in the search results table. However, I explained that it wasn't really "working" before. I was doing the sorting on the frontend, but it was only sorting with the first 100 rows or so, so the sort was not global (basically not correct). So the feature was never really there in the first place.

Now I have hooked up the backend sorting capabilities to the frontend, but there are some limitations:

- Trying to [sort by name](https://mygeneset.info/v1/query?sort=-name%2C-id&size=10&fields=all&always_list=genes%2Cgenes.alias%2Cgenes.entrezgene%2Cgenes.symbol%2Cgenes.ensembl%2Cgenes.ensemblgene%2Cgenes.uniprot) throws a "fielddata" error. Not sure if this is a flag I can pass with the request, or if it's some kind of Elastic Search option that needs to be set.
- Elastic Search perhaps doesn't support sorting by the "count" of an array field.

**Comment by vincerubinetti** [comment]
@ravila4 With my last few commits, I believe I've incorporated or addressed all of your suggestions. Namely:

- use pill/capsule shapes around genes for better readability
- use gene symbols instead of names when listing genes for more compact display (fully details available on hover)
- on the browse page, add controls to filter by user/curated/anonymous and kegg/go/wikipathways/etc
- enable sorting by author, source, and gene count (split author/source into separate columns)
- make selected list of genes on geneset page be searchable and sortable
- show dump/upload dates when geneset is curated

I've also updated the bulleted list at the top of this PR with the changes.

**Comment by vincerubinetti** [comment]
I am going to be out-of-office starting tomorrow, and I'll be back on 6/29. As such, I'd like to merge this today and test it out a bit in production.

Ricardo seems to be out-of-office at the moment as well, so I'm going to merge this without explicit approval (though through Slack he thought the changes to the PR looked good).

**Comment by ravila4** [comment]
>     some curated geneset names are blank.
I'm almost done testing a PR to fix this issue with MSIGDB  genesets, I opted to parse a different file that actually contains the name and other metadata. https://github.com/biothings/mygeneset.info/pull/48/files
It needs some optimization, because it ran very slow, but I can already make a new release that has all geneset names.

>     count top level field needs to be added for genesets, so i can display and sort by them
Still testing this, I tried doing the counting at the mongoDB level instead of the parser, so that I didn't have to edit all plugins: https://github.com/biothings/mygeneset.info/pull/49

>     upload_date and dump_date/download_date for curated sources need to be added to the /metadata endpoint
The feature has been implemented in this PR, but needs some minor fixes: https://github.com/newgene/biothings.api/pull/30

**Pull request merged**
