### PR TITLE
Add basic geneset download format options, and more

### PR DESCRIPTION
**Pull request by vincerubinetti**
- change styling of checkbox
- add radio button styling
- add checklist component for list of checkboxes and radio buttons
- add heading to codeblock component
- add download util funcs
- comment tooltip directive more
- convert try it out page to checklist component
- add download section to geneset page with basic format options

image

### CODE REVIEW

**Comment by ravila4** [comment]
Some issues to consider:

1. Some download formats (csv, tsv, and gmt)  are designed to hold multiple genesets. Therefore, the best location for a download button is actually below the geneset [Browse](https://deploy-preview-21--my-geneset.netlify.app/browse) page, or the [Your Genesets](https://deploy-preview-21--my-geneset.netlify.app/build) table. On the other hand, I think that the JSON format works well with the current implementation.

2. Multi-geneset file formats and ID fields that have multiple values. For example, when using  ensembl ID as the identifier. If a gene has multiple ensembl ids, the user may want to keep only the first item from the list, especially if the file format is CSV or TSV.

**Comment by arjunkrish** [comment]
The netlify app looks beautiful!
The gene ID, format, and transpose options are all great.

My one suggestion is to see if it's possible to have a more compact layout of this page:

MyGeneset

**Comment by vincerubinetti** [comment]
> My one suggestion is to see if it's possible to have a more compact layout of this page:

I don't think that will be possible:

1. The title of genesets [can be very long](https://deploy-preview-21--my-geneset.netlify.app/geneset/VECCHI_GASTRIC_CANCER_ADVANCED_VS_EARLY_DN)
2. The descriptions (when users start making genesets) will likely be very long
3. The selected and add gene tables both have many columns
4. The download formatting options are going to be quite elaborate and wide

There's just too much information to display on that page.

1 and 2 could be solved by truncating with ellipses, having a scroll bar, or clicking/hovering to see the full thing, but I've found in the past that users can frustrated by this. 

3 could be solved if we could eliminate all but one column and had a more complex, surefire way to choose an identifier to show. We could pick the first available identifier in order of the most common identifiers, but I could also see users being frustrated by not seeing their desired identifier. We'd also have to implement something more complex for the Add Genes section, to make sure the identifier that was matched in the search was always shown as the column of choice. Overall, probably too complex and inconsistent (leading to user confusion). If one, recognizable identifier was always available on every gene, I'd use that, but there doesn't appear to be one.

4 could be solved if we were much more opinionated on how the user should format the geneset. For example, only allowing one identifier, nixing the transpose option. And of course the preview would probably have to go, as having a tiny scroll window for a giant json or tsv would be frustrating.

**Comment by vincerubinetti** [comment]
@ravila4 

1. It seems like CSV and TSV could also be used to store a single geneset with multiple identifiers. Maybe GMX doesn't belong there though. 

Also I didn't think downloading groups of genesets was in the scope of this project. But I guess I could see it being useful on the "user genesets" page. And also maybe under the browse page results, like when wanting to download all the genesets of a particular species.

2. Currently it's just "flattening" fields with multiple values in place, eg `["gene 1 symbol a", ["gene 2 symbol a", "gene 2 symbol b"]]` -> `["gene 1 symbol a", "gene 2 symbol a", "gene 2 symbol b"]`. I could add an option to pick the first and an option to do it by a chosen delimiter.

Overall, we need user feedback on this, on what formats and options are the most useful. But since I have this working on the front end, I'd like to use this as an opportunity to decide what the functionality should be when it's implemented on the backend as well, so I don't have to change a bunch of things when that gets implemented, and also so people can look at the UI and intuitively figure out what options they would need (the preview helps I think).

**Comment by ravila4** [comment]
`It seems like CSV and TSV could also be used to store a single geneset with multiple identifiers. Maybe GMX doesn't belong there though.`

That's a good point, let's keep the current options. I think downloading multiple genesets in one file will be useful for several use cases, but we can leave that feature for another PR.

`Currently it's just "flattening" fields with multiple values in place, eg ["gene 1 symbol a", ["gene 2 symbol a", "gene 2 symbol b"]] -> ["gene 1 symbol a", "gene 2 symbol a", "gene 2 symbol b"]. I could add an option to pick the first and an option to do it by a chosen delimiter.`

I think all three methods have use cases.

**Comment by cgreene** [comment]
The download options look pretty good to me 👍

**Comment by vincerubinetti** [comment]
@ravila4 Can we merge this now so I can proceed. I'm sure we'll get user feedback later that will result in this being revisited and tweaked.

**Pull request merged**
