### PR TITLE
Add basic api page

### PR DESCRIPTION
**Pull request by vincerubinetti**
- add basic api page with hero component, link to docs, and try now sections
- refactor headings to utilize h2's
- tweak css
- build page title heading into main component
- add codeblock component with code input component
- refactor inappropriate use of `ref()`
- remove unnecessary uses of methods and put toggle right in click handlers
- make prettyjson component that shows indented, highlighted, collapsible tree view of json provided to it
- add some debug functions to sleep and generate dummy json data
- add download json util func

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Test here:
https://deploy-preview-5--my-geneset.netlify.app/api

Note, clicking "Run" just generates random json data for now.

**Comment by vincerubinetti** [comment]
@dongbohu @cgreene

**Comment by cgreene** [comment]
What does that version refer to? The API version, the backend, or something else? The page itself looks nice to me :)

**Comment by vincerubinetti** [comment]
That will be the API version, like they list for their other APIs, eg [mygene api](https://mygene.info/v3/api)

**Comment by cgreene** [comment]
Got it! 👍

**Pull request merged**
